package lexer;
/* The following code was generated by JFlex 1.6.1 */


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2009  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Use together with unicode.flex for Unicode preprocesssing */
/* and java12.cup for a Java 1.2 parser                      */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals,
   because the input is read twice and the methods used to parse
   the numbers are not very fast.
   For a production quality application (e.g. a Java compiler)
   this could be optimized */


import java_cup.runtime.*;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/manan/Spaces/Projects/emj-compiler/src/lexer/JFlexInput.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;

    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    /**
     * lexical states
     */
    public static final int YYINITIAL = 0;
    public static final int STRING = 2;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     * at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0, 1, 1
    };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\0\1\3\1\2\1\73\1\74\1\1\22\0\1\3\1\57\1\62" +
                    "\3\0\1\53\1\72\1\43\1\44\1\5\1\60\1\52\1\61\1\42" +
                    "\1\4\1\10\1\64\1\63\1\70\1\65\1\11\1\71\1\66\1\67" +
                    "\1\11\1\0\1\51\1\56\1\55\3\0\22\6\1\31\7\6\1\47" +
                    "\1\12\1\50\1\0\1\7\1\0\1\15\1\21\1\13\1\26\1\34" +
                    "\1\36\1\33\1\40\1\22\2\6\1\14\1\27\1\30\1\25\1\17" +
                    "\1\6\1\32\1\16\1\23\1\20\1\24\1\37\1\35\1\41\1\6" +
                    "\1\45\1\54\1\46\7\0\1\73\u1fa2\0\1\73\1\73\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\2\0\1\1\2\2\1\3\1\4\1\5\2\6\17\5" +
                    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16" +
                    "\1\17\2\1\1\20\1\21\1\22\1\23\1\24\1\25" +
                    "\1\26\2\27\1\1\1\30\1\2\1\0\7\5\1\31" +
                    "\14\5\1\32\1\33\1\34\1\0\1\35\1\36\1\37" +
                    "\1\40\1\41\1\42\1\43\1\44\1\45\2\0\6\5" +
                    "\1\46\4\5\1\47\7\5\2\0\6\5\1\50\1\51" +
                    "\1\52\1\53\3\5\1\54\3\5\1\0\1\55\1\5" +
                    "\1\56\7\5\1\57\1\60\1\0\1\61\1\62\1\63" +
                    "\1\5\1\64\1\5\1\65\1\5\1\0\1\66\1\0" +
                    "\1\67\10\0\1\70\6\0\1\71";

    private static int[] zzUnpackAction() {
        int[] result = new int[164];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\75\0\172\0\267\0\172\0\364\0\172\0\u0131" +
                    "\0\172\0\u016e\0\u01ab\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc" +
                    "\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4" +
                    "\0\u0501\0\172\0\172\0\172\0\172\0\172\0\172\0\172" +
                    "\0\172\0\172\0\u053e\0\u057b\0\u05b8\0\172\0\172\0\172" +
                    "\0\u05f5\0\172\0\u0632\0\u066f\0\172\0\u06ac\0\172\0\u06e9" +
                    "\0\u0726\0\u0763\0\u07a0\0\u07dd\0\u081a\0\u0857\0\u0894\0\u08d1" +
                    "\0\u0131\0\u090e\0\u094b\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c" +
                    "\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\172\0\172\0\172" +
                    "\0\u0bea\0\172\0\172\0\172\0\172\0\172\0\172\0\172" +
                    "\0\172\0\172\0\u0c27\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58" +
                    "\0\u0d95\0\u0dd2\0\u0131\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0131" +
                    "\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae" +
                    "\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\u1259\0\u0131" +
                    "\0\u0131\0\u0131\0\u0131\0\u1296\0\u12d3\0\u1310\0\u0131\0\u134d" +
                    "\0\u138a\0\u13c7\0\u1404\0\u0131\0\u1441\0\u0131\0\u147e\0\u14bb" +
                    "\0\u14f8\0\u1535\0\u1572\0\u15af\0\u15ec\0\u0131\0\u0131\0\u1629" +
                    "\0\u0131\0\u0131\0\u0131\0\u1666\0\u0131\0\u16a3\0\u0131\0\u16e0" +
                    "\0\u171d\0\u0131\0\u175a\0\u0131\0\u1797\0\u17d4\0\u1811\0\u184e" +
                    "\0\u188b\0\u18c8\0\u1905\0\u1942\0\172\0\u197f\0\u19bc\0\u19f9" +
                    "\0\u1a36\0\u1a73\0\u1ab0\0\172";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[164];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11" +
                    "\1\12\1\3\1\13\1\14\1\10\1\15\1\16\1\10" +
                    "\1\17\1\20\1\21\1\22\2\10\1\23\1\24\1\25" +
                    "\1\26\1\10\1\27\1\10\1\30\1\31\2\10\1\32" +
                    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42" +
                    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52" +
                    "\7\12\1\3\1\0\1\5\1\53\1\54\1\55\7\53" +
                    "\1\56\47\53\1\57\12\53\77\0\1\5\76\0\1\60" +
                    "\1\61\75\0\4\10\1\0\27\10\21\0\7\10\13\0" +
                    "\2\12\51\0\7\12\11\0\4\10\1\0\1\10\1\62" +
                    "\25\10\21\0\7\10\11\0\4\10\1\0\21\10\1\63" +
                    "\5\10\21\0\7\10\11\0\4\10\1\0\7\10\1\64" +
                    "\1\65\16\10\21\0\7\10\11\0\4\10\1\0\5\10" +
                    "\1\66\21\10\21\0\7\10\11\0\4\10\1\0\12\10" +
                    "\1\67\14\10\21\0\7\10\11\0\4\10\1\0\15\10" +
                    "\1\70\5\10\1\71\3\10\21\0\7\10\11\0\4\10" +
                    "\1\0\17\10\1\72\5\10\1\73\1\10\21\0\7\10" +
                    "\11\0\4\10\1\0\12\10\1\74\14\10\21\0\7\10" +
                    "\11\0\4\10\1\0\2\10\1\75\24\10\21\0\7\10" +
                    "\11\0\4\10\1\0\21\10\1\76\5\10\21\0\7\10" +
                    "\11\0\4\10\1\0\10\10\1\77\15\10\1\100\21\0" +
                    "\7\10\11\0\4\10\1\0\21\10\1\101\5\10\21\0" +
                    "\7\10\11\0\4\10\1\0\1\10\1\102\20\10\1\103" +
                    "\4\10\21\0\7\10\11\0\4\10\1\0\2\10\1\104" +
                    "\24\10\21\0\7\10\11\0\4\10\1\0\25\10\1\105" +
                    "\1\10\21\0\7\10\56\0\1\106\75\0\1\107\75\0" +
                    "\1\110\102\0\1\111\11\0\1\53\2\0\7\53\1\0" +
                    "\47\53\1\0\12\53\2\0\1\55\72\0\1\112\2\0" +
                    "\7\112\1\113\6\112\1\114\1\112\1\115\4\112\1\116" +
                    "\1\112\1\117\3\112\1\120\23\112\1\121\7\112\1\122" +
                    "\2\0\1\60\1\4\1\5\72\60\5\123\1\124\67\123" +
                    "\6\0\4\10\1\0\2\10\1\125\24\10\21\0\7\10" +
                    "\11\0\4\10\1\0\15\10\1\126\11\10\21\0\7\10" +
                    "\11\0\4\10\1\0\13\10\1\127\13\10\21\0\7\10" +
                    "\11\0\4\10\1\0\2\10\1\130\24\10\21\0\7\10" +
                    "\11\0\4\10\1\0\6\10\1\131\20\10\21\0\7\10" +
                    "\11\0\4\10\1\0\12\10\1\132\14\10\21\0\7\10" +
                    "\11\0\4\10\1\0\10\10\1\133\16\10\21\0\7\10" +
                    "\11\0\4\10\1\0\5\10\1\134\21\10\21\0\7\10" +
                    "\11\0\4\10\1\0\7\10\1\135\17\10\21\0\7\10" +
                    "\11\0\4\10\1\0\7\10\1\136\17\10\21\0\7\10" +
                    "\11\0\4\10\1\0\7\10\1\137\17\10\21\0\7\10" +
                    "\11\0\4\10\1\0\24\10\1\140\2\10\21\0\7\10" +
                    "\11\0\4\10\1\0\17\10\1\141\7\10\21\0\7\10" +
                    "\11\0\4\10\1\0\3\10\1\142\23\10\21\0\7\10" +
                    "\11\0\4\10\1\0\10\10\1\143\16\10\21\0\7\10" +
                    "\11\0\4\10\1\0\3\10\1\144\23\10\21\0\7\10" +
                    "\11\0\4\10\1\0\10\10\1\145\16\10\21\0\7\10" +
                    "\11\0\4\10\1\0\1\10\1\146\25\10\21\0\7\10" +
                    "\11\0\4\10\1\0\7\10\1\147\17\10\21\0\7\10" +
                    "\67\0\1\150\10\0\5\123\1\151\67\123\4\0\1\5" +
                    "\1\124\75\0\4\10\1\0\3\10\1\152\23\10\21\0" +
                    "\7\10\11\0\4\10\1\0\20\10\1\153\6\10\21\0" +
                    "\7\10\11\0\4\10\1\0\21\10\1\154\5\10\21\0" +
                    "\7\10\11\0\4\10\1\0\10\10\1\155\16\10\21\0" +
                    "\7\10\11\0\4\10\1\0\1\10\1\156\25\10\21\0" +
                    "\7\10\11\0\4\10\1\0\1\10\1\157\25\10\21\0" +
                    "\7\10\11\0\4\10\1\0\21\10\1\160\5\10\21\0" +
                    "\7\10\11\0\4\10\1\0\3\10\1\161\23\10\21\0" +
                    "\7\10\11\0\4\10\1\0\13\10\1\162\13\10\21\0" +
                    "\7\10\11\0\4\10\1\0\15\10\1\163\11\10\21\0" +
                    "\7\10\11\0\4\10\1\0\7\10\1\164\17\10\21\0" +
                    "\7\10\11\0\4\10\1\0\10\10\1\165\16\10\21\0" +
                    "\7\10\11\0\4\10\1\0\5\10\1\166\21\10\21\0" +
                    "\7\10\11\0\4\10\1\0\21\10\1\167\5\10\21\0" +
                    "\7\10\11\0\4\10\1\0\21\10\1\170\5\10\21\0" +
                    "\7\10\11\0\4\10\1\0\3\10\1\171\23\10\21\0" +
                    "\7\10\11\0\4\10\1\0\1\10\1\172\25\10\21\0" +
                    "\7\10\70\0\1\173\7\0\4\123\1\5\1\151\67\123" +
                    "\6\0\4\10\1\0\3\10\1\174\23\10\21\0\7\10" +
                    "\11\0\4\10\1\0\10\10\1\175\16\10\21\0\7\10" +
                    "\11\0\4\10\1\0\23\10\1\176\3\10\21\0\7\10" +
                    "\11\0\4\10\1\0\7\10\1\177\17\10\21\0\7\10" +
                    "\11\0\4\10\1\0\7\10\1\200\17\10\21\0\7\10" +
                    "\11\0\4\10\1\0\21\10\1\201\5\10\21\0\7\10" +
                    "\11\0\4\10\1\0\15\10\1\202\11\10\21\0\7\10" +
                    "\11\0\4\10\1\0\21\10\1\203\5\10\21\0\7\10" +
                    "\11\0\4\10\1\0\17\10\1\204\7\10\21\0\7\10" +
                    "\11\0\4\10\1\0\15\10\1\205\11\10\21\0\7\10" +
                    "\11\0\4\10\1\0\21\10\1\206\5\10\21\0\7\10" +
                    "\11\0\4\10\1\0\21\10\1\207\5\10\21\0\7\10" +
                    "\71\0\1\210\14\0\4\10\1\0\25\10\1\211\1\10" +
                    "\21\0\7\10\11\0\4\10\1\0\1\212\26\10\21\0" +
                    "\7\10\11\0\4\10\1\0\1\213\26\10\21\0\7\10" +
                    "\11\0\4\10\1\0\2\10\1\214\24\10\21\0\7\10" +
                    "\11\0\4\10\1\0\20\10\1\215\6\10\21\0\7\10" +
                    "\11\0\4\10\1\0\14\10\1\216\12\10\21\0\7\10" +
                    "\11\0\4\10\1\0\15\10\1\217\11\10\21\0\7\10" +
                    "\11\0\4\10\1\0\13\10\1\220\13\10\21\0\7\10" +
                    "\70\0\1\221\15\0\4\10\1\0\15\10\1\222\11\10" +
                    "\21\0\7\10\11\0\4\10\1\0\27\10\1\223\20\0" +
                    "\7\10\11\0\4\10\1\0\3\10\1\224\23\10\21\0" +
                    "\7\10\72\0\1\225\32\0\1\226\137\0\1\227\24\0" +
                    "\1\230\145\0\1\231\26\0\1\232\136\0\1\233\51\0" +
                    "\1\234\121\0\1\235\24\0\1\236\107\0\1\237\64\0" +
                    "\1\240\102\0\1\241\67\0\1\242\65\0\1\243\110\0" +
                    "\1\244\44\0";

    private static int[] zzUnpackTrans() {
        int[] result = new int[6893];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unknown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\2\0\1\11\1\1\1\11\1\1\1\11\1\1\1\11" +
                    "\20\1\11\11\3\1\3\11\1\1\1\11\2\1\1\11" +
                    "\1\1\1\11\1\1\1\0\24\1\3\11\1\0\11\11" +
                    "\2\0\23\1\2\0\21\1\1\0\14\1\1\0\10\1" +
                    "\1\0\1\1\1\0\1\1\10\0\1\11\6\0\1\11";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[164];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the input device
     */
    private java.io.Reader zzReader;

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * number of newlines encountered up to the start of the matched text
     */
    private int yyline;

    /**
     * the number of characters up to the start of the matched text
     */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /**
     * denotes if the user-EOF-code has already been executed
     */
    private boolean zzEOFDone;

    /**
     * The number of occupied positions in zzBuffer beyond zzEndRead.
     * When a lead/high surrogate has been read from the input stream
     * into the final zzBuffer position, this will have a value of 1;
     * otherwise, it will have a value of 0.
     */
    private int zzFinalHighSurrogate = 0;

    /* user code: */
    StringBuilder string = new StringBuilder();

    private EMJavaSymbol symbol(int type) {
        return new EMJavaSymbol(type, yyline + 1, yycolumn + 1);
    }

    private EMJavaSymbol symbol(int type, Object value) {
        return new EMJavaSymbol(type, yyline + 1, yycolumn + 1, value);
    }

    /**
     * assumes correct representation of a long value for
     * specified radix in scanner buffer from <code>start</code>
     * to <code>end</code>
     */
    private long parseLong(int start, int end, int radix) {
        long result = 0;
        long digit;

        for (int i = start; i < end; i++) {
            digit = Character.digit(yycharat(i), radix);
            result *= radix;
            result += digit;
        }

        return result;
    }


    /**
     * Creates a new scanner
     *
     * @param in the java.io.Reader to read input from.
     */
    public Lexer(java.io.Reader in) {
        this.zzReader = in;
    }


    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x110000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 190) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }


    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

            /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
            /* if not: blow it up */
            char newBuffer[] = new char[zzBuffer.length * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
        }

        /* fill the buffer with new input */
        int requested = zzBuffer.length - zzEndRead;
        int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

        /* not supposed to occur according to specification of java.io.Reader */
        if (numRead == 0) {
            throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
        }
        if (numRead > 0) {
            zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
            if (numRead == requested) {
                if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
                    --zzEndRead;
                    zzFinalHighSurrogate = 1;
                }
            }
            /* potentially more input available */
            return false;
        }

        /* numRead < 0 ==> end of stream */
        return true;
    }


    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */
        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null)
            zzReader.close();
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     * <p>
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     * <p>
     * Internal scan buffer is resized down to its initial length, if it has grown.
     *
     * @param reader the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        zzFinalHighSurrogate = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
        if (zzBuffer.length > ZZ_BUFFERSIZE)
            zzBuffer = new char[ZZ_BUFFERSIZE];
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead + pos];
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Contains user EOF-code, which will be executed exactly once,
     * when the end of file is reached
     */
    private void zzDoEOF() throws java.io.IOException {
        if (!zzEOFDone) {
            zzEOFDone = true;
            yyclose();
        }
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public java_cup.runtime.Symbol next_token() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            boolean zzR = false;
            int zzCh;
            int zzCharCount;
            for (zzCurrentPosL = zzStartRead;
                 zzCurrentPosL < zzMarkedPosL;
                 zzCurrentPosL += zzCharCount) {
                zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
                zzCharCount = Character.charCount(zzCh);
                switch (zzCh) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR)
                            zzR = false;
                        else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn += zzCharCount;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL)
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                else if (zzAtEOF)
                    zzPeek = false;
                else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof)
                        zzPeek = false;
                    else
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                }
                if (zzPeek) yyline--;
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ((zzAttributes & 1) == 1) {
                zzAction = zzState;
            }


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true;
                zzDoEOF();
                {
                    return symbol(SymbolMapping.symbolsMap.get("EOF"));
                }
            } else {
                switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                    case 1: {
                        throw new RuntimeException("Illegal character \"" + yytext() +
                                "\" at line " + yyline + ", column " + yycolumn);
                    }
                    case 58:
                        break;
                    case 2: { /* ignore */
                    }
                    case 59:
                        break;
                    case 3: {
                        return symbol(SymbolMapping.symbolsMap.get("DIVIDE"));
                    }
                    case 60:
                        break;
                    case 4: {
                        return symbol(SymbolMapping.symbolsMap.get("MULTIPLY"));
                    }
                    case 61:
                        break;
                    case 5: {
                        return symbol(SymbolMapping.symbolsMap.get("ID"), yytext());
                    }
                    case 62:
                        break;
                    case 6: {
                        return symbol(SymbolMapping.symbolsMap.get("INT_LITERAL"), new Integer(yytext()));
                    }
                    case 63:
                        break;
                    case 7: {
                        return symbol(SymbolMapping.symbolsMap.get("DOT"));
                    }
                    case 64:
                        break;
                    case 8: {
                        return symbol(SymbolMapping.symbolsMap.get("LPAREN"));
                    }
                    case 65:
                        break;
                    case 9: {
                        return symbol(SymbolMapping.symbolsMap.get("RPAREN"));
                    }
                    case 66:
                        break;
                    case 10: {
                        return symbol(SymbolMapping.symbolsMap.get("LBRACE"));
                    }
                    case 67:
                        break;
                    case 11: {
                        return symbol(SymbolMapping.symbolsMap.get("RBRACE"));
                    }
                    case 68:
                        break;
                    case 12: {
                        return symbol(SymbolMapping.symbolsMap.get("LBRACK"));
                    }
                    case 69:
                        break;
                    case 13: {
                        return symbol(SymbolMapping.symbolsMap.get("RBRACK"));
                    }
                    case 70:
                        break;
                    case 14: {
                        return symbol(SymbolMapping.symbolsMap.get("SEMICOLON"));
                    }
                    case 71:
                        break;
                    case 15: {
                        return symbol(SymbolMapping.symbolsMap.get("COMMA"));
                    }
                    case 72:
                        break;
                    case 16: {
                        return symbol(SymbolMapping.symbolsMap.get("EQ"));
                    }
                    case 73:
                        break;
                    case 17: {
                        return symbol(SymbolMapping.symbolsMap.get("LT"));
                    }
                    case 74:
                        break;
                    case 18: {
                        return symbol(SymbolMapping.symbolsMap.get("NOT"));
                    }
                    case 75:
                        break;
                    case 19: {
                        return symbol(SymbolMapping.symbolsMap.get("PLUS"));
                    }
                    case 76:
                        break;
                    case 20: {
                        return symbol(SymbolMapping.symbolsMap.get("MINUS"));
                    }
                    case 77:
                        break;
                    case 21: {
                        string.setLength(0);
                        yybegin(STRING);
                    }
                    case 78:
                        break;
                    case 22: {
                        string.append(yytext());
                    }
                    case 79:
                        break;
                    case 23: {
                        throw new RuntimeException("Unterminated string at end of line");
                    }
                    case 80:
                        break;
                    case 24: {
                        yybegin(YYINITIAL);
                        return symbol(SymbolMapping.symbolsMap.get("STRING_LITERAL"),
                                string.toString());
                    }
                    case 81:
                        break;
                    case 25: {
                        return symbol(SymbolMapping.symbolsMap.get("IF"));
                    }
                    case 82:
                        break;
                    case 26: {
                        return symbol(SymbolMapping.symbolsMap.get("AND"));
                    }
                    case 83:
                        break;
                    case 27: {
                        return symbol(SymbolMapping.symbolsMap.get("OR"));
                    }
                    case 84:
                        break;
                    case 28: {
                        return symbol(SymbolMapping.symbolsMap.get("DEQ"));
                    }
                    case 85:
                        break;
                    case 29: {
                        throw new RuntimeException("Illegal escape sequence \"" + yytext() + "\"");
                    }
                    case 86:
                        break;
                    case 30: {
                        string.append('\\');
                    }
                    case 87:
                        break;
                    case 31: {
                        string.append('\b');
                    }
                    case 88:
                        break;
                    case 32: {
                        string.append('\t');
                    }
                    case 89:
                        break;
                    case 33: {
                        string.append('\n');
                    }
                    case 90:
                        break;
                    case 34: {
                        string.append('\r');
                    }
                    case 91:
                        break;
                    case 35: {
                        string.append('\f');
                    }
                    case 92:
                        break;
                    case 36: {
                        string.append('\"');
                    }
                    case 93:
                        break;
                    case 37: {
                        string.append('\'');
                    }
                    case 94:
                        break;
                    case 38: {
                        return symbol(SymbolMapping.symbolsMap.get("INT"));
                    }
                    case 95:
                        break;
                    case 39: {
                        return symbol(SymbolMapping.symbolsMap.get("NEW"));
                    }
                    case 96:
                        break;
                    case 40: {
                        return symbol(SymbolMapping.symbolsMap.get("BOOLEAN_LITERAL"), true);
                    }
                    case 97:
                        break;
                    case 41: {
                        return symbol(SymbolMapping.symbolsMap.get("THIS"));
                    }
                    case 98:
                        break;
                    case 42: {
                        return symbol(SymbolMapping.symbolsMap.get("VOID"));
                    }
                    case 99:
                        break;
                    case 43: {
                        return symbol(SymbolMapping.symbolsMap.get("MAIN"));
                    }
                    case 100:
                        break;
                    case 44: {
                        return symbol(SymbolMapping.symbolsMap.get("ELSE"));
                    }
                    case 101:
                        break;
                    case 45: {
                        return symbol(SymbolMapping.symbolsMap.get("CLASS"));
                    }
                    case 102:
                        break;
                    case 46: {
                        return symbol(SymbolMapping.symbolsMap.get("SIDEF"));
                    }
                    case 103:
                        break;
                    case 47: {
                        return symbol(SymbolMapping.symbolsMap.get("BOOLEAN_LITERAL"), false);
                    }
                    case 104:
                        break;
                    case 48: {
                        return symbol(SymbolMapping.symbolsMap.get("WHILE"));
                    }
                    case 105:
                        break;
                    case 49: {
                        return symbol(SymbolMapping.symbolsMap.get("LENGTH"));
                    }
                    case 106:
                        break;
                    case 50: {
                        return symbol(SymbolMapping.symbolsMap.get("STATIC"));
                    }
                    case 107:
                        break;
                    case 51: {
                        return symbol(SymbolMapping.symbolsMap.get("PUBLIC"));
                    }
                    case 108:
                        break;
                    case 52: {
                        return symbol(SymbolMapping.symbolsMap.get("STRING"));
                    }
                    case 109:
                        break;
                    case 53: {
                        return symbol(SymbolMapping.symbolsMap.get("RETURN"));
                    }
                    case 110:
                        break;
                    case 54: {
                        return symbol(SymbolMapping.symbolsMap.get("BOOLEAN"));
                    }
                    case 111:
                        break;
                    case 55: {
                        return symbol(SymbolMapping.symbolsMap.get("EXTENDS"));
                    }
                    case 112:
                        break;
                    case 56: {
                        return symbol(SymbolMapping.symbolsMap.get("INT_LITERAL"), new Integer(Integer.MIN_VALUE));
                    }
                    case 113:
                        break;
                    case 57: {
                        return symbol(SymbolMapping.symbolsMap.get("PRINTLN"));
                    }
                    case 114:
                        break;
                    default:
                        zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }

    /**
     * Converts an int token code into the name of the
     * token by reflection on the cup symbol class/interface sym
     * <p>
     * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
     */
    private String getTokenName(int token) {
        try {
            java.lang.reflect.Field[] classFields = Symbol.class.getFields();
            for (int i = 0; i < classFields.length; i++) {
                if (classFields[i].getInt(null) == token) {
                    return classFields[i].getName();
                }
            }
        } catch (Exception e) {
            e.printStackTrace(System.err);
        }

        return "UNKNOWN TOKEN";
    }

    /**
     * Same as next_token but also prints the token to standard out
     * for debugging.
     * <p>
     * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
     */
    public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
        java_cup.runtime.Symbol s = next_token();
        System.out.println("line:" + (yyline + 1) + " col:" + (yycolumn + 1) + " --" + yytext() + "--" + getTokenName(s.sym) + "--");
        return s;
    }

    /**
     * Runs the scanner on input files.
     * <p>
     * This main method is the debugging routine for the scanner.
     * It prints debugging information about each returned token to
     * System.out until the end of file is reached, or an error occured.
     *
     * @param argv the command line, contains the filenames to run
     *             the scanner on.
     */
    public static void main(String argv[]) {
        if (argv.length == 0) {
            System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
        } else {
            int firstFilePos = 0;
            String encodingName = "UTF-8";
            if (argv[0].equals("--encoding")) {
                firstFilePos = 2;
                encodingName = argv[1];
                try {
                    java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid?
                } catch (Exception e) {
                    System.out.println("Invalid encoding '" + encodingName + "'");
                    return;
                }
            }
            for (int i = firstFilePos; i < argv.length; i++) {
                Lexer scanner = null;
                try {
                    java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
                    java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
                    scanner = new Lexer(reader);
                    while (!scanner.zzAtEOF) scanner.debug_next_token();
                } catch (java.io.FileNotFoundException e) {
                    System.out.println("File not found : \"" + argv[i] + "\"");
                } catch (java.io.IOException e) {
                    System.out.println("IO error scanning file \"" + argv[i] + "\"");
                    System.out.println(e);
                } catch (Exception e) {
                    System.out.println("Unexpected exception:");
                    e.printStackTrace();
                }
            }
        }
    }


}
